language: node_js

node_js:
  - '8'
  - '9'

cache:
  directories:
    - node_modules

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --v1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - sleep 5

sudo: false

script:
  - "yarn run lint"
  - "yarn run test"
  - "yarn run build"
