dist: bionic

addons:
  apt:
    packages:
      - libgconf-2-4

language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

git:
  quiet: true

cache:
  yarn: true
  directories:
    - ~/.cache

install:
  - yarn install --frozen-lockfile

script:
  - "yarn lint"
  - "yarn build"
